TMDB_API:
MOVIE_TEMPLATE: "\
{{target_path}}/\
{% if video_format == 'HEVC'}Movies_HEVC/\
{% elsif video_format == '2K' or video_format == '4K' }Movies_HQ/\
{% else %}Movies/\
{%endif%}\
{{title}} ({{year}}) {% if tag %}{{tag}} {% endif %}[{{video_format}}]/\
{{title}} ({{year}}) {% if tag %}{{tag}} {% endif %}[{{video_format}}] \
{% if video_codec == 'HEVC' %}[HEVC] {%endif%}\
[{{audio_codec}}].{{ext}}"
TV_TEMPLATE: "test"
